//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentedBooksInfo
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public string Shelf { get; set; }
        public string Genre { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public string Notes { get; set; }
        public int RentId { get; set; }
        public int Book_Id { get; set; }
        public int User_Id { get; set; }
        public System.DateTime Return_date { get; set; }
        public System.DateTime Rent_date { get; set; }
        public string Status { get; set; }
        public int UserId { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string E_mail { get; set; }
        public int Type { get; set; }
        public string ToPay { get; set; }
    }
}
